# Generated by Django 3.2.5 on 2021-07-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KR', 'КЫРГЫЗСКИЙ'), ('RU', 'РУССКИЙ')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='News_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Оглавление')),
                ('header_title', models.CharField(max_length=1000, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('add_date', models.DateField(verbose_name='Дата начало')),
                ('edit_date', models.DateField(verbose_name='Дата изменения')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.filter')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.language')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order_num', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('news_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsapp.news_details')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.language'),
        ),
    ]
